# Settings.yml
---
conf.py:
  project: Getting Started Tutorial
  copyright: 2004-2013
  version: 1.0.1
  release: 1.0.1
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted
    github_branch: 1-0
  latex_documents:
  - - Index
    - t3start.tex
    - Getting Started Tutorial
    - Documentation Team
    - manual

  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
